const PAYMENT_STATUS = {
  CREATED: 'CREATED',
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUND_REQUESTED: 'REFUND_REQUESTED',
  REFUNDED: 'REFUNDED',
  CANCELED: 'CANCELED',
};
export { PAYMENT_STATUS };
